name: Development deployment

concurrency: frontend-dev-ev

# These actions happen whenever someone pushes or creates a pull request to the dev branch
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
jobs:
  dev-deployment:
    runs-on: ubuntu-latest
    environment: frontend-dev-ev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Deploy to A2 Hosting
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.A2HOSTING_PRIVATE_KEY }}
        passphrase: ${{ secrets.A2HOSTING_PRIVATE_KEY_PASSPHRASE }}
        source: "build/"
        # strip_components set to 1 stops a "build" folder from being created at the destination https://github.com/appleboy/scp-action/issues/59#issuecomment-964605479
        strip_components: 1
        target: ${{ secrets.SFTP_DEV_FRONTEND_DESTINATION_PATH }}